"""init clean

Revision ID: 9455496b71f5
Revises: 
Create Date: 2026-04-17 23:10:42.693267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9455496b71f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_progli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('No_seri', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=100), nullable=False),
    sa.Column('jam_masuk', sa.String(length=100), nullable=False),
    sa.Column('jam_keluar', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('kelas', sa.Integer(), nullable=True),
    sa.Column('email', sa.Integer(), nullable=True),
    sa.Column('email_verified', sa.String(length=100), nullable=False),
    sa.Column('finger_id', sa.Integer(), nullable=False),
    sa.Column('alamat', sa.String(length=50), nullable=False),
    sa.Column('no_tlp', sa.Integer(), nullable=True),
    sa.Column('prodi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prodi_id'], ['data_progli.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_verified'),
    sa.UniqueConstraint('finger_id')
    )
    op.create_table('absensi_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.Integer(), nullable=True),
    sa.Column('waktu', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tanggal', sa.Integer(), nullable=True),
    sa.Column('siswa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['data_siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absensi_siswa')
    op.drop_table('data_siswa')
    op.drop_table('user')
    op.drop_table('jadwal')
    op.drop_table('device')
    op.drop_table('data_progli')
    # ### end Alembic commands ###
